### ISSUE TITLE
PV LevelPage SkillRelatedTaskLevel: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by jani270** [NotEnoughUpdates/NotEnoughUpdates#1076]
```
java.lang.IndexOutOfBoundsException: Index: 7, Size: 7
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.google.gson.JsonArray.get(JsonArray.java:101)
	at io.github.moulberry.notenoughupdates.profileviewer.level.task.SkillRelatedTaskLevel.drawTask(SkillRelatedTaskLevel.java:98)
	at io.github.moulberry.notenoughupdates.profileviewer.level.LevelPage.lambda$drawPage$0(LevelPage.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at io.github.moulberry.notenoughupdates.profileviewer.level.LevelPage.drawPage(LevelPage.java:95)
	at io.github.moulberry.notenoughupdates.profileviewer.BasicPage.drawPage(BasicPage.java:143)
	at io.github.moulberry.notenoughupdates.profileviewer.GuiProfileViewer.drawScreen(GuiProfileViewer.java:436)
```
Guy you can test it;
https://namemc.com/profile/ApexReflex.1?q=043aca923f8341fface0242833330990

**Comment by NopoTheGamer** [comment]
this looks fixed? doesnt crash me
