### ISSUE TITLE
NEU x Oneconfig: ClassCastException

### ISSUE THREAD

**Issue by jani270** [NotEnoughUpdates/NotEnoughUpdates#1127]
```
java.lang.ClassCastException: io.github.moulberry.notenoughupdates.options.separatesections.Mining$GlaciteTunnelWaypointBehaviour cannot be cast to java.lang.Integer
	at cc.polyfrost.oneconfig.gui.elements.config.ConfigDropdown.draw(ConfigDropdown.java:119)
	at cc.polyfrost.oneconfig.config.elements.OptionSubcategory.draw(OptionSubcategory.java:97)
	at cc.polyfrost.oneconfig.gui.pages.ModConfigPage.draw(ModConfigPage.java:87)
	at cc.polyfrost.oneconfig.gui.pages.Page.scrollWithDraw(Page.java:106)
	at cc.polyfrost.oneconfig.gui.OneConfigGui.draw(OneConfigGui.java:297)
	at cc.polyfrost.oneconfig.utils.gui.OneUIScreen.lambda$onDrawScreen$0(OneUIScreen.java:80)
	at cc.polyfrost.oneconfig.utils.gui.OneUIScreen$$Lambda$1124/1504892695.accept(Unknown Source)
	at cc.polyfrost.oneconfig.internal.renderer.NanoVGHelperImpl.setupAndDraw(NanoVGHelperImpl.java:146)
	at cc.polyfrost.oneconfig.internal.renderer.NanoVGHelperImpl.setupAndDraw(NanoVGHelperImpl.java:111)
	at cc.polyfrost.oneconfig.utils.gui.OneUIScreen.onDrawScreen(OneUIScreen.java:80)
	at cc.polyfrost.oneconfig.libs.universal.UScreen.onDrawScreen(UScreen.kt:220)
	at cc.polyfrost.oneconfig.libs.universal.UScreen$onDrawScreenCompat$1.invoke(UScreen.kt:226)
	at cc.polyfrost.oneconfig.libs.universal.UScreen$onDrawScreenCompat$1.invoke(UScreen.kt:224)
	at cc.polyfrost.oneconfig.libs.universal.UMatrixStack$Compat.runLegacyMethod(UMatrixStack.kt:288)
	at cc.polyfrost.oneconfig.libs.universal.UScreen.onDrawScreenCompat(UScreen.kt:224)
	at cc.polyfrost.oneconfig.libs.universal.UScreen.drawScreen(UScreen.kt:133)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1436)
```

**Comment by Wyvest** [comment]
This seems to be an issue with the NEU compat layer and not due to a native OneConfig issue
