### ISSUE TITLE
TimersOverlay: Heavy Pearls NumberFormatException

### ISSUE THREAD

**Issue by jani270** [NotEnoughUpdates/NotEnoughUpdates#788]
```
[21:48:50] [Client thread/INFO]: [io.github.moulberry.notenoughupdates.overlays.TimersOverlay:processActionBar:1095]: java.lang.NumberFormatException: For input string: "3    ?????"
[21:48:50] [Client thread/INFO]: [io.github.moulberry.notenoughupdates.overlays.TimersOverlay:processActionBar:1095]: 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[21:48:50] [Client thread/INFO]: [io.github.moulberry.notenoughupdates.overlays.TimersOverlay:processActionBar:1095]: 	at java.lang.Integer.parseInt(Integer.java:580)
[21:48:50] [Client thread/INFO]: [io.github.moulberry.notenoughupdates.overlays.TimersOverlay:processActionBar:1095]: 	at java.lang.Integer.parseInt(Integer.java:615)
[21:48:50] [Client thread/INFO]: [io.github.moulberry.notenoughupdates.overlays.TimersOverlay:processActionBar:1095]: 	at io.github.moulberry.notenoughupdates.overlays.TimersOverlay.processActionBar(TimersOverlay.java:1093)
[21:48:50] [Client thread/INFO]: [io.github.moulberry.notenoughupdates.overlays.TimersOverlay:processActionBar:1095]: 	at io.github.moulberry.notenoughupdates.listener.ChatListener.onGuiChat(ChatListener.java:196)
```

**Comment by NopoTheGamer** [comment]
it looks like this got fixed ages ago
